# Generated by Django 6.0.1 on 2026-02-03 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
