# Generated by Django 6.0.1 on 2026-02-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_consume_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20),
        ),
    ]
