# Generated by Django 6.0.1 on 2026-07-01 09:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_consume_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='meal',
        ),
        migrations.AddField(
            model_name='consume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consume',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=50),
        ),
        migrations.AddField(
            model_name='consume',
            name='quantity_grams',
            field=models.FloatField(default=100, help_text='Quantity consumed in grams'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('grains', 'Grains'), ('dairy', 'Dairy'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('snacks', 'Snacks'), ('fast_food', 'Fast Food'), ('beverages', 'Beverages'), ('nonvegetarian', 'Non-Vegetarian'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(help_text='Calories per 100 grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(help_text='Carbs per 100 grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(help_text='Fat per 100 grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(help_text='Protein per 100 grams'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters', null=True)),
                ('current_weight_kg', models.FloatField(blank=True, help_text='Current weight in kilograms', null=True)),
                ('target_weight_kg', models.FloatField(blank=True, help_text='Target weight in kilograms', null=True)),
                ('goal_type', models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=20)),
                ('activity_level', models.CharField(choices=[('low', 'Low Activity'), ('moderate', 'Moderate Activity'), ('high', 'High Activity')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
